// D2Q9 BGK solver. Grid/lattice units only. No artificial vorticity forcing.
export class CylinderLBM {
 constructor(W=320,H=128,Re=100){this.W=W;this.H=H;this.N=W*H;this.U=.06;this.D=20;this.Re=Re;this.nu=this.U*this.D/Re;this.omega=1/(.5+3*this.nu);this.cx=[0,1,0,-1,0,1,-1,-1,1];this.cy=[0,0,1,0,-1,1,1,-1,-1];this.opp=[0,3,4,1,2,7,8,5,6];this.w=[4/9,1/9,1/9,1/9,1/9,1/36,1/36,1/36,1/36];this.a=new Float32Array(this.N*9);this.b=new Float32Array(this.N*9);this.mask=new Uint8Array(this.N);this.neighbors=new Int32Array(this.N*9);for(let y=0;y<H;y++)for(let x=0;x<W;x++)for(let q=0;q<9;q++){let sx=x-this.cx[q],sy=(y-this.cy[q]+H)%H;this.neighbors[(y*W+x)*9+q]=sx<0?-1:sx>=W?-2:sy*W+sx;}this.samples=[];this.steps=0;this.force=[0,0];
 for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=y*W+x;this.mask[i]=Math.hypot(x-64,y-64.3)<10?1:0;let uy=.0001*Math.sin(2*Math.PI*y/H);for(let q=0;q<9;q++)this.a[i*9+q]=this.eq(q,1,this.U,uy);}
 }
 eq(q,r,u,v){let c=3*(this.cx[q]*u+this.cy[q]*v);return this.w[q]*r*(1+c+.5*c*c-1.5*(u*u+v*v));}
 step(){const {W,H,N,a,b,cx,cy,opp,w,mask,omega,U,neighbors}=this;let fx=0,fy=0;const f=new Float64Array(9);for(let i=0;i<N;i++){if(mask[i])continue;let y=(i/W)|0,x=i-y*W,r=0,u=0,v=0;for(let q=0;q<9;q++){let j=neighbors[i*9+q];let z;if(j===-1)z=w[q]*(1+3*cx[q]*U+4.5*cx[q]*cx[q]*U*U-1.5*U*U);else if(j===-2)z=a[(y*W+W-1)*9+q];else if(mask[j]){z=a[i*9+opp[q]];fx-=2*z*cx[q];fy-=2*z*cy[q];}else z=a[j*9+q];f[q]=z;r+=z;u+=cx[q]*z;v+=cy[q]*z;}u/=r;v/=r;if(x===0){r=1;u=U;v=0;}let uu=1.5*(u*u+v*v);for(let q=0;q<9;q++){let c=3*(cx[q]*u+cy[q]*v);b[i*9+q]=f[q]+omega*(w[q]*r*(1+c+.5*c*c-uu)-f[q]);}}
 this.a=b;this.b=a;this.steps++;this.force=[fx,fy];if(this.steps%10===0)this.samples.push([this.steps,fx,fy]);if(this.samples.length>4000)this.samples.shift();
 }
 field(){let ux=new Float32Array(this.N),uy=new Float32Array(this.N),rho=new Float32Array(this.N),rgba=new Uint8Array(this.N*4);let finite=true,max=0;for(let i=0;i<this.N;i++){if(this.mask[i]){rho[i]=1;continue;}let r=0,u=0,v=0;for(let q=0;q<9;q++){let f=this.a[i*9+q];r+=f;u+=this.cx[q]*f;v+=this.cy[q]*f;}ux[i]=u/r;uy[i]=v/r;rho[i]=r;finite&&=Number.isFinite(r)&&r>.1&&r<3;max=Math.max(max,Math.hypot(u/r,v/r));}for(let y=0;y<this.H;y++)for(let x=0;x<this.W;x++){let i=y*this.W+x,j=i*4;let vort=(uy[y*this.W+Math.min(x+1,this.W-1)]-uy[y*this.W+Math.max(x-1,0)]-ux[((y+1)%this.H)*this.W+x]+ux[((y-1+this.H)%this.H)*this.W+x])*.5;let t=Math.max(-1,Math.min(1,vort/.007));let k=Math.abs(t);rgba[j]=t>0?30+220*k:20;rgba[j+1]=35+120*(1-k);rgba[j+2]=t<0?50+205*k:60;rgba[j+3]=255;if(this.mask[i]){rgba[j]=224;rgba[j+1]=238;rgba[j+2]=239;}}return {rgba,finite,max};}
 strouhal(){let s=this.samples.filter(s=>s[0]>=12000);if(s.length<500)return null;let mean=s.reduce((a,b)=>a+b[2],0)/s.length,ys=s.map(x=>x[2]-mean),cross=[];for(let i=1;i<ys.length;i++)if(ys[i-1]<=0&&ys[i]>0)cross.push(s[i-1][0]+10*(-ys[i-1])/(ys[i]-ys[i-1]));if(cross.length<4)return null;let period=(cross.at(-1)-cross[0])/(cross.length-1);return {value:this.D/(this.U*period),period,cycles:cross.length-1,start:s[0][0],end:s.at(-1)[0]};}
}
