import {warmSeed} from './warmseed.js';
import {voxelMask,airfoilGeometry,rotationQuaternion} from './shapes.js';
import {warm3D} from './warm3d.js';
import * as THREE from 'three';
export const C3=[[0,0,0],[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1],[1,1,0],[-1,-1,0],[1,-1,0],[-1,1,0],[1,0,1],[-1,0,-1],[1,0,-1],[-1,0,1],[0,1,1],[0,-1,-1],[0,1,-1],[0,-1,1]];
const O=C3.map(c=>C3.findIndex(d=>d.every((v,k)=>v===-c[k]))),W=C3.map((c,i)=>i===0?1/3:c.filter(v=>v!==0).length===1?1/18:1/36);
export class LBM3D {
 constructor(renderer,{grid=[128,64,32],Re=250,shape='cylinder',warm=false,U=.08,seeded=false,seedWarm=false,rotation=[0,0,0]}={}){this.rotation=rotation;const rotated=rotation.some(v=>Math.abs(v)>1e-8);if(rotated){warm=false;seedWarm=false;}const inv=new THREE.Matrix3().setFromMatrix4(new THREE.Matrix4().makeRotationFromQuaternion(rotationQuaternion(rotation).invert()));const rotGLSL=Array.from(inv.elements).map(v=>v.toFixed(12)).join(',');this.renderer=renderer;if(grid[0]*8>renderer.capabilities.maxTextureSize||grid[1]*Math.ceil(grid[2]/8)>renderer.capabilities.maxTextureSize)throw Error('Grid exceeds GPU texture size limit.');if(renderer.getContext().getParameter(renderer.getContext().MAX_DRAW_BUFFERS)<3)throw Error('D3Q19 needs at least three float color attachments.');this.N=grid;this.Re=Re;this.shape=shape;this.seedWarm=seedWarm;this.D=grid[1]*.1875;this.U=U;this.nu=this.U*this.D/Re;this.tau=.5+3*this.nu;this.odd=.5+.001/(this.tau-.5);this.steps=0;this.history=[];this.width=grid[0]*8;this.height=grid[1]*Math.ceil(grid[2]/8);this.targets=[0,1].map(()=>[3,2].map(count=>new THREE.WebGLRenderTarget(this.width,this.height,{count,type:THREE.FloatType,format:THREE.RGBAFormat,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:false,stencilBuffer:false})));
 this.macro=new THREE.WebGLRenderTarget(this.width,this.height,{type:THREE.FloatType,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:false});this.scene=new THREE.Scene();this.camera=new THREE.Camera();this.quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2));this.scene.add(this.quad);this.uniforms={f0:{value:null},f1:{value:null},f2:{value:null},f3:{value:null},f4:{value:null},initialize:{value:1},warmField:{value:null},useWarm:{value:(warm||seedWarm)?1:0},shapeMask:{value:null}};
 const base=`precision highp float;precision highp int;uniform sampler2D f0,f1,f2,f3,f4;uniform int initialize,useWarm;uniform sampler2D warmField,shapeMask;const vec3 N=vec3(${grid.map(x=>x+'.').join(',')});const vec2 A=vec2(${this.width}.,${this.height}.);const float U=${this.U},D=${this.D.toFixed(5)},wp=${(1/this.tau).toFixed(12)},wm=${(1/this.odd).toFixed(12)};const vec3 C[19]=vec3[19](${C3.map(c=>'vec3('+c.map(v=>v+'.').join(',')+')').join(',')});const float W[19]=float[19](${W.map(w=>w.toFixed(12)).join(',')});const int O[19]=int[19](${O.join(',')});vec2 uv(vec3 p){p.yz=mod(p.yz+N.yz,N.yz);p.x=clamp(p.x,0.,N.x-1.);return (vec2(mod(p.z,8.)*N.x+ p.x,floor(p.z/8.)*N.y+p.y)+.5)/A;}vec3 cell(){vec2 q=floor(gl_FragCoord.xy);return vec3(mod(q.x,N.x),mod(q.y,N.y),floor(q.x/N.x)+8.*floor(q.y/N.y));}bool solid(vec3 p){vec3 center=vec3(N.x*.25,N.y*.5+${["sphere","cylinder","airfoil"].includes(shape)?".17":"0."},N.z*.5);vec3 d=mat3(${rotGLSL})*(p-center);vec3 localP=d+center;return ${shape==='airfoil'?'(abs(d.z)<D*.35 && d.x>-D*.5 && d.x<D*.5 && abs(d.y)<5.*.12*D*(.2969*sqrt(max(0.,d.x/D+.5))-.126*(d.x/D+.5)-.3516*pow(d.x/D+.5,2.)+.2843*pow(d.x/D+.5,3.)-.1036*pow(d.x/D+.5,4.)))':!['cylinder','sphere'].includes(shape)?'(all(greaterThanEqual(localP,vec3(0.))) && all(lessThan(localP,N)) && texture(shapeMask,uv(floor(localP+.5))).r>.5)':(shape==='sphere'?'length(d)<D*.5':rotated?'(length(d.xy)<D*.5 && abs(d.z)<N.z*.5)':'length(d.xy)<D*.5')};}float eq(int i,vec3 u,float rho){float cu=dot(C[i],u);return W[i]*rho*(1.+3.*cu+4.5*cu*cu-1.5*dot(u,u));}float readf(int i,vec3 p){vec2 q=uv(p);if(i<4)return texture(f0,q)[i];if(i<8)return texture(f1,q)[i-4];if(i<12)return texture(f2,q)[i-8];if(i<16)return texture(f3,q)[i-12];return texture(f4,q)[i-16];}void compute(out float g[19],out vec4 m){vec3 p=cell();if(p.z>=N.z){for(int i=0;i<19;i++)g[i]=W[i];m=vec4(0,0,0,1);return;}if(initialize==1){vec3 u=vec3(U,.001*U*sin(p.x*.23)*cos(6.283*p.z/N.z),.001*U*sin(p.y*.31)*sin(6.283*p.z/N.z));${seeded?'u.yz+=.01*U*vec2(fract(sin(dot(p,vec3(12.9898,78.233,37.719)))*43758.5453)-.5,fract(sin(dot(p,vec3(93.9898,67.345,54.123)))*23421.631)-.5);':''}float r=1.;if(useWarm==1){vec4 v=texture(warmField,uv(p));u=v.xyz;r=v.w;}if(solid(p))u=vec3(0);for(int i=0;i<19;i++)g[i]=eq(i,u,r);m=vec4(u,r);return;}if(solid(p)){for(int i=0;i<19;i++)g[i]=W[i];m=vec4(0,0,0,1);return;}float a[19];float rho=0.;vec3 u=vec3(0);for(int i=0;i<19;i++){vec3 s=p-C[i];float v;if(s.x<0.)v=eq(i,vec3(U,0,0),1.);else if(solid(s))v=readf(O[i],p);else v=readf(i,s);a[i]=v;rho+=v;u+=v*C[i];}u/=max(rho,.00001);if(p.x<1.){u=vec3(U,0,0);rho=1.;for(int i=0;i<19;i++)a[i]=eq(i,u,rho);}m=vec4(u,rho);for(int i=0;i<19;i++){int j=O[i];float ei=eq(i,u,rho),ej=eq(j,u,rho);g[i]=a[i]-wp*.5*(a[i]+a[j]-ei-ej)-wm*.5*(a[i]-a[j]-ei+ej);}}`;
 this.base=base;const vertex='void main(){gl_Position=vec4(position.xy,0.,1.);}';this.materials=[0,1].map((group)=>{const start=group*12,count=group===0?3:2;return new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,uniforms:this.uniforms,vertexShader:vertex,fragmentShader:base+Array.from({length:count},(_,i)=>`layout(location=${i}) out vec4 out${i};`).join('')+`void main(){float g[19];vec4 m;compute(g,m);`+Array.from({length:count},(_,i)=>`out${i}=vec4(${Array.from({length:4},(_,j)=>start+i*4+j<19?`g[${start+i*4+j}]`:'0.').join(',')});`).join('')+'}'});});
 this.macroMat=new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,uniforms:this.uniforms,vertexShader:vertex,fragmentShader:base+'out vec4 color;void main(){vec3 p=cell();vec3 u=vec3(0);float rho=0.;for(int i=0;i<19;i++){float v=readf(i,p);rho+=v;u+=v*C[i];}color=vec4(solid(p)?vec3(0):u/max(rho,.00001),rho);}'});if(!['cylinder','sphere'].includes(shape)){const geometry=shape==='airfoil'?airfoilGeometry():undefined,m=voxelMask([{type:shape,size:3,pos:[16,16,16],geometry}]);let data=new Float32Array(this.width*this.height*4);for(let z=0;z<grid[2];z++)for(let y=0;y<grid[1];y++)for(let x=0;x<grid[0];x++){let xx=Math.min(63,Math.floor(x/grid[0]*64)),yy=Math.min(31,Math.floor(y/grid[1]*32)),zz=Math.max(0,Math.min(31,Math.floor((z-grid[2]*.5)/(grid[1]/32)+16)));data[((Math.floor(z/8)*grid[1]+y)*this.width+(z%8)*grid[0]+x)*4]=m.owners[(zz*32+yy)*64+xx]>=0?1:0;}this.shapeTexture=new THREE.DataTexture(data,this.width,this.height,THREE.RGBAFormat,THREE.FloatType);this.shapeTexture.needsUpdate=true;this.uniforms.shapeMask.value=this.shapeTexture;geometry?.dispose();}if((warm&&shape==='cylinder'&&Re===250)||(seedWarm&&shape==='cylinder'&&Re===300)){let data=new Float32Array(this.width*this.height*4);for(let z=0;z<grid[2];z++)for(let y=0;y<grid[1];y++)for(let x=0;x<grid[0];x++){const pos=[x/grid[0]*32,y/grid[1]*16,z/grid[2]*(seedWarm?8:4)],b=pos.map(Math.floor),f=pos.map((v,i)=>v-b[i]);for(let k=0;k<4;k++){let v=0;for(let dz=0;dz<2;dz++)for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++){let xx=Math.min(31,b[0]+dx),yy=(b[1]+dy)%16,zz=(b[2]+dz)%(seedWarm?8:4);v+=(seedWarm?warmSeed:warm3D)[((zz*16+yy)*32+xx)*4+k]*(dx?f[0]:1-f[0])*(dy?f[1]:1-f[1])*(dz?f[2]:1-f[2]);}data[((Math.floor(z/8)*grid[1]+y)*this.width+(z%8)*grid[0]+x)*4+k]=v;}}this.warmTexture=new THREE.DataTexture(data,this.width,this.height,THREE.RGBAFormat,THREE.FloatType);this.warmTexture.needsUpdate=true;this.uniforms.warmField.value=this.warmTexture;}else this.uniforms.useWarm.value=0;this.bind(this.targets[1]);for(let j=0;j<2;j++)this.render(this.materials[j],this.targets[0][j]);this.uniforms.initialize.value=0;this.forceTarget=new THREE.WebGLRenderTarget(this.width,this.height,{type:THREE.FloatType,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:false});this.forceMat=new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,uniforms:this.uniforms,vertexShader:vertex,fragmentShader:base+'out vec4 color;void main(){vec3 p=cell();vec3 force=vec3(0);if(!solid(p)&&p.z<N.z)for(int i=1;i<19;i++)if(solid(p+C[i]))force+=2.*readf(i,p)*C[i];color=vec4(force,0);}'});this.updateMacro();}
 render(mat,target){this.quad.material=mat;this.renderer.setRenderTarget(target);this.renderer.render(this.scene,this.camera);this.renderer.setRenderTarget(null);}
 bind(set){let t=[...set[0].textures,...set[1].textures];t.forEach((t,i)=>this.uniforms['f'+i].value=t);}
 step(n=1){for(let k=0;k<n;k++){this.bind(this.targets[0]);for(let j=0;j<2;j++)this.render(this.materials[j],this.targets[1][j]);this.targets.reverse();this.steps++;}this.bind(this.targets[0]);}
 updateMacro(){this.bind(this.targets[0]);this.render(this.macroMat,this.macro);}
 field(){this.updateMacro();let a=new Float32Array(this.width*this.height*4);this.renderer.readRenderTargetPixels(this.macro,0,0,this.width,this.height,a);let max=0,finite=true,minR=Infinity,maxR=-Infinity,wz2=0;for(let i=0;i<a.length;i+=4){let u=Math.hypot(a[i],a[i+1],a[i+2]);finite&&=Number.isFinite(u)&&Number.isFinite(a[i+3]);max=Math.max(max,u);minR=Math.min(minR,a[i+3]);maxR=Math.max(maxR,a[i+3]);wz2+=a[i+2]**2;}return {data:a,finite,max,minR,maxR,spanwiseRms:Math.sqrt(wz2/(a.length/4)),steps:this.steps};}
 forces(){this.bind(this.targets[0]);this.render(this.forceMat,this.forceTarget);let a=new Float32Array(this.width*this.height*4);this.renderer.readRenderTargetPixels(this.forceTarget,0,0,this.width,this.height,a);let f=[0,0,0];for(let i=0;i<a.length;i+=4)for(let j=0;j<3;j++)f[j]+=a[i+j];let area=this.shape==='sphere'?Math.PI*this.D*this.D/4:this.D*this.N[2],norm=.5*this.U*this.U*area;let d={steps:this.steps,force:f,Cd:f[0]/norm,Cl:f[1]/norm,Cz:f[2]/norm};this.history.push(d);return d;}
 strouhal(){let a=this.history.filter(d=>d.steps>(this.uniforms.useWarm.value?600:this.D/this.U*20));if(a.length<10)return null;let mean=a.reduce((s,d)=>s+d.Cl,0)/a.length,amp=Math.max(...a.map(d=>d.Cl))-Math.min(...a.map(d=>d.Cl));if(amp<.005)return null;let crossings=[];for(let i=1;i<a.length;i++)if(a[i-1].Cl<mean&&a[i].Cl>=mean)crossings.push(a[i-1].steps+(a[i].steps-a[i-1].steps)*(mean-a[i-1].Cl)/(a[i].Cl-a[i-1].Cl));if(crossings.length<5)return null;let period=(crossings.at(-1)-crossings[0])/(crossings.length-1);return {value:this.D/(this.U*period),period,cycles:crossings.length-1,start:a[0].steps,end:a.at(-1).steps};}
 dispose(){this.warmTexture?.dispose();this.shapeTexture?.dispose();this.forceTarget.dispose();this.forceMat.dispose();this.targets.flat().forEach(t=>t.dispose());this.macro.dispose();this.materials.forEach(m=>m.dispose());this.macroMat.dispose();}
}
