import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {FluidSolver,prelude} from './solver.js';
import './style.css';
import {S,NX,NY,NZ,W,H} from './grid.js';
import {makeShape,disposeShape,importGeometry,airfoilGeometry} from './shapes.js';
const $=id=>document.getElementById(id);
try {
 const renderer=new THREE.WebGLRenderer({antialias:true});
 if(!renderer.capabilities.isWebGL2||!renderer.extensions.has('EXT_color_buffer_float'))throw new Error('This app needs WebGL2 and floating-point render targets. Use a recent desktop Chrome, Firefox, or Safari with hardware acceleration.');
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('viewport').appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#0a141e');const camera=new THREE.PerspectiveCamera(45,1,.1,500);camera.position.set(96,68,105);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(32,16,16);controls.enableDamping=true;
 scene.add(new THREE.AmbientLight('#9dbbcf',2));const light=new THREE.DirectionalLight('#ffffff',3);light.position.set(25,60,30);scene.add(light);
 const tunnel=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(64,32,32)),new THREE.LineBasicMaterial({color:'#284b60',transparent:true,opacity:.75}));tunnel.position.set(32,16,16);scene.add(tunnel);
 const grid=new THREE.GridHelper(64,16,'#294b5c','#193142');grid.position.set(32,0,16);scene.add(grid);
 const arrow=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(-5,16,16),9,'#68e1b6',2,1);scene.add(arrow);
 const solver=new FluidSolver(renderer);const shapes=[];let selected=0;let running=true;let serial=0;
 const meshFor=makeShape;
 function refresh(reset=true){shapes.forEach(s=>{if(s.mesh){scene.remove(s.mesh);disposeShape(s.mesh);}s.mesh=meshFor(s);scene.add(s.mesh);});solver.setShapes(shapes);if(reset)solver.reset();$('selected').innerHTML=shapes.map((s,i)=>`<option value="${i}">${(s.label||s.type).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')} ${s.id}</option>`).join('');$('selected').value=selected;const s=shapes[selected];['size','position','height','depth','remove','rotation-x','rotation-y','rotation-z'].forEach(id=>$(id).disabled=!s);if(s){s.rotation??=[0,0,0];['x','y','z'].forEach((axis,i)=>{$('rotation-'+axis).value=s.rotation[i];$('rotation-'+axis+'-value').textContent=s.rotation[i]+'°';});$('size').value=s.size;$('size-value').textContent=s.size;$('position').value=s.pos[0];$('height').value=s.pos[1];$('depth').value=s.pos[2];}$('add').disabled=shapes.length>=12;}
 function add(){if(shapes.length>=12)return;shapes.push({type:$('shape').value,geometry:$('shape').value==='airfoil'?airfoilGeometry():undefined,size:5,pos:[26+Math.min(shapes.length,3)*7,16,16],id:++serial});selected=shapes.length-1;refresh();}
 $('add').onclick=add;$('selected').onchange=e=>{selected=Number(e.target.value);refresh(false);};$('remove').onclick=()=>{const s=shapes[selected];if(!s)return;scene.remove(s.mesh);disposeShape(s.mesh);if(s.geometry)s.geometry.dispose();shapes.splice(selected,1);selected=Math.max(0,selected-1);refresh();};
 ['size','position','height','depth'].forEach((id,i)=>$(id).oninput=()=>{const s=shapes[selected];if(!s)return;if(i===0)s.size=+$(id).value;else s.pos[i-1]=+$(id).value;refresh();});
 ['x','y','z'].forEach((axis,i)=>$('rotation-'+axis).oninput=()=>{const s=shapes[selected];if(!s)return;s.rotation??=[0,0,0];s.rotation[i]=+$('rotation-'+axis).value;refresh();});
 $('speed').oninput=()=>{solver.inlet=+$('speed').value;$('speed-value').textContent=solver.inlet.toFixed(1);};$('viscosity').oninput=()=>{solver.viscosity=+$('viscosity').value;$('viscosity-value').textContent=solver.viscosity.toFixed(3);};$('toggle').onclick=()=>{running=!running;$('toggle').textContent=running?'Pause':'Run';$('state').textContent=running?'LIVE':'PAUSED';};$('reset').onclick=()=>solver.reset();
 add();
 const total=8192,geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(total*3),3));const ids=new Float32Array(total);for(let i=0;i<total;i++)ids[i]=i;geometry.setAttribute('pid',new THREE.BufferAttribute(ids,1));
 const particleMat=new THREE.ShaderMaterial({uniforms:{...solver.uniforms,points:{value:solver.particles[0].texture}},vertexShader:prelude+`uniform sampler2D points;attribute float pid;varying float speed;uniform sampler2D curlField;uniform float curlScale;varying vec4 tint;vec3 sampleCurl(vec3 p){p*=${S}.;p=clamp(p,vec3(.5),vec3(${NX-.5},${NY-.5},${NZ-.5}));float z=clamp(p.z-.5,0.,${NZ-1}.999),z0=floor(z),z1=z0+1.;vec2 a=(vec2(mod(z0,8.)*${NX}.,floor(z0/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);vec2 b=(vec2(mod(z1,8.)*${NX}.,floor(z1/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);return mix(texture2D(curlField,a).xyz,texture2D(curlField,b).xyz,fract(z));}void main(){vec2 uv=vec2(mod(pid,128.)+.5,floor(pid/128.)+.5)/vec2(128.,64.);vec3 p=texture2D(points,uv).xyz;speed=length(linearVelocity(p))/${S}.;vec3 w=sampleCurl(p),aw=abs(w);float dom=aw.x>=aw.y&&aw.x>=aw.z?w.x:aw.y>=aw.z?w.y:w.z;tint=vec4(dom>=0.?vec3(1.,.19,.12):vec3(.12,.48,1.),smoothstep(.018,.30,length(w)*curlScale));vec4 mv=modelViewMatrix*vec4(p/${S}.,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(150./-mv.z,1.5,4.);}`,fragmentShader:`precision highp float;varying float speed;varying vec4 tint;void main(){if(length(gl_PointCoord-.5)>.5)discard;vec3 c=mix(vec3(.12,.4,.85),vec3(.32,.88,.73),clamp(speed,0.,1.));c=mix(c,vec3(1.,.91,.52),clamp(speed-1.,0.,1.));c=mix(c,tint.rgb,tint.a*.9);gl_FragColor=vec4(c,.50);}`,transparent:true,depthWrite:false});
 const points=new THREE.Points(geometry,particleMat);points.frustumCulled=false;scene.add(points);
 const trailGeo=new THREE.BufferGeometry();trailGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(total*6),3));const trailIds=new Float32Array(total*2),ends=new Float32Array(total*2);for(let i=0;i<total;i++){trailIds[i*2]=trailIds[i*2+1]=i;ends[i*2+1]=1;}trailGeo.setAttribute('pid',new THREE.BufferAttribute(trailIds,1));trailGeo.setAttribute('end',new THREE.BufferAttribute(ends,1));
 const trails=new THREE.LineSegments(trailGeo,new THREE.ShaderMaterial({uniforms:particleMat.uniforms,vertexShader:prelude+`uniform sampler2D points;attribute float pid;attribute float end;varying float speed;uniform sampler2D curlField;uniform float curlScale;varying vec4 tint;vec3 sampleCurl(vec3 p){p*=${S}.;p=clamp(p,vec3(.5),vec3(${NX-.5},${NY-.5},${NZ-.5}));float z=clamp(p.z-.5,0.,${NZ-1}.999),z0=floor(z),z1=z0+1.;vec2 a=(vec2(mod(z0,8.)*${NX}.,floor(z0/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);vec2 b=(vec2(mod(z1,8.)*${NX}.,floor(z1/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);return mix(texture2D(curlField,a).xyz,texture2D(curlField,b).xyz,fract(z));}void main(){vec2 uv=vec2(mod(pid,128.)+.5,floor(pid/128.)+.5)/vec2(128.,64.);vec3 p=texture2D(points,uv).xyz;vec3 u=linearVelocity(p);speed=length(u)/${S}.;vec3 w=sampleCurl(p),aw=abs(w);float dom=aw.x>=aw.y&&aw.x>=aw.z?w.x:aw.y>=aw.z?w.y:w.z;tint=vec4(dom>=0.?vec3(1.,.19,.12):vec3(.12,.48,1.),smoothstep(.018,.30,length(w)*curlScale));p-=u*end*.9;gl_Position=projectionMatrix*modelViewMatrix*vec4(p/${S}.,1.);}`,fragmentShader:`precision highp float;varying float speed;varying vec4 tint;void main(){vec3 c=mix(vec3(.12,.4,.85),vec3(.32,.88,.73),clamp(speed,0.,1.));c=mix(c,vec3(1.,.91,.52),clamp(speed-1.,0.,1.));c=mix(c,tint.rgb,tint.a*.9);gl_FragColor=vec4(c,.22);}`,transparent:true,depthWrite:false}));trails.frustumCulled=false;scene.add(trails);
 // Actual center-plane velocity deficit: a wake can be seen even when tracers obscure it.
 const wakeMat=new THREE.ShaderMaterial({uniforms:solver.uniforms,vertexShader:prelude+`varying vec3 p;void main(){p=vec3(uv.x*64.,uv.y*32.,16.);gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:prelude+`varying vec3 p;void main(){vec3 pg=p*${S}.;if(solid(pg))discard;vec3 u=linearVelocity(pg);float deficit=clamp(1.-u.x/max(inlet,.01),0.,1.);if(deficit<.05)discard;gl_FragColor=vec4(mix(vec3(.12,.42,.95),vec3(1.,.45,.1),deficit),deficit*.55);}`,transparent:true,depthWrite:false,side:THREE.DoubleSide});
 const wakePlane=new THREE.Mesh(new THREE.PlaneGeometry(1,1),wakeMat);wakePlane.frustumCulled=false;scene.add(wakePlane);

 // Ray-marched advected scalar density, not geometry-attached or scripted smoke.
 const smokeUniforms={curlField:{value:solver.curl.texture},curlTint:{value:1},curlScale:{value:4},density:{value:solver.dye[0].texture},eye:{value:camera.position}};particleMat.uniforms.curlField=smokeUniforms.curlField;particleMat.uniforms.curlScale=smokeUniforms.curlScale;
 const volumeMat=new THREE.ShaderMaterial({uniforms:smokeUniforms,vertexShader:`varying vec3 world;void main(){world=(modelMatrix*vec4(position,1)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(world,1);}`,fragmentShader:`precision highp float;uniform sampler2D density,curlField;uniform float curlTint,curlScale;uniform vec3 eye;varying vec3 world;
 vec3 sampleCurl(vec3 p){p*=${S}.;p=clamp(p,vec3(.5),vec3(${NX-.5},${NY-.5},${NZ-.5}));float z=clamp(p.z-.5,0.,${NZ-1}.999),z0=floor(z),z1=z0+1.;vec2 a=(vec2(mod(z0,8.)*${NX}.,floor(z0/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);vec2 b=(vec2(mod(z1,8.)*${NX}.,floor(z1/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);return mix(texture2D(curlField,a).xyz,texture2D(curlField,b).xyz,fract(z));}
 float d(vec3 p){p*=${S}.;if(any(lessThan(p,vec3(.5)))||any(greaterThan(p,vec3(${NX-.5},${NY-.5},${NZ-.5}))))return 0.;float z=clamp(p.z-.5,0.,${NZ-1}.999),z0=floor(z),z1=z0+1.;vec2 a=(vec2(mod(z0,8.)*${NX}.,floor(z0/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);vec2 b=(vec2(mod(z1,8.)*${NX}.,floor(z1/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);return mix(texture2D(density,a).r,texture2D(density,b).r,fract(z));}

 void main(){vec3 ray=normalize(world-eye);vec3 t0=(vec3(0)-eye)/ray,t1=(vec3(64,32,32)-eye)/ray;vec3 lo=min(t0,t1),hi=max(t0,t1);float near=max(max(lo.x,lo.y),lo.z),far=min(min(hi.x,hi.y),hi.z);near=max(near,0.);vec4 sum=vec4(0);float stride=(far-near)/48.;for(int i=0;i<48;i++){vec3 p=eye+ray*(near+(float(i)+.5)*stride);float rho=d(p);float a=1.-exp(-rho*stride*.22);float shade=exp(-d(p+vec3(-1,2,1))*1.8);vec3 color=mix(vec3(.27,.44,.50),vec3(.86,.96,.94),shade);if(curlTint>.5){vec3 w=sampleCurl(p),aw=abs(w);float dominant=aw.x>=aw.y&&aw.x>=aw.z?w.x:aw.y>=aw.z?w.y:w.z;float saturation=smoothstep(.018,.30,length(w)*curlScale);vec3 hue=dominant>=0.?vec3(1.,.19,.12):vec3(.12,.48,1.);color=mix(color,hue*(.65+.35*shade),saturation*.92);}sum.rgb+=(1.-sum.a)*a*color;sum.a+=(1.-sum.a)*a;if(sum.a>.96)break;}if(sum.a<.005)discard;gl_FragColor=vec4(sum.rgb/max(sum.a,.001),sum.a);}`,side:THREE.BackSide,transparent:true,depthWrite:false});
 const volume=new THREE.Mesh(new THREE.BoxGeometry(64,32,32),volumeMat);volume.position.set(32,16,16);volume.renderOrder=2;scene.add(volume);
 function setVisual(){document.querySelector('.legend').style.display=['smoke','curl-smoke'].includes($('visual-style').value)?'none':'';const smoke=['smoke','curl-smoke'].includes($('visual-style').value);smokeUniforms.curlTint.value=$('visual-style').value==='curl-smoke'?1:0;volume.visible=smoke;wakePlane.visible=$('visual-style').value==='slice';points.visible=!smoke;trails.visible=!smoke;}
 $('visual-style').onchange=setVisual;setVisual();
 $('curl-contrast').oninput=()=>{smokeUniforms.curlScale.value=+$('curl-contrast').value;};
 $('swirl').oninput=()=>{solver.confinement=+$('swirl').value;};
 $('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Keep the file below 10 MB.');if(shapes.length>=12)throw Error('Remove a shape first.');$('import-status').textContent='Voxelizing...';const geometry=importGeometry(file.name,await file.arrayBuffer());shapes.push({type:'mesh',geometry,label:file.name.replace(/[<>]/g,''),size:5,pos:[26,16,16],id:++serial});selected=shapes.length-1;refresh();$('import-status').textContent='Imported. Closed/watertight meshes work best.';}catch(e){$('import-status').textContent=e.message;}$('import').value='';};
 $('grid-quality').value=S===1?'standard':'high';$('grid-footer').textContent=`GPU stable fluids · ${NX} × ${NY} × ${NZ}`;$('grid-quality').onchange=()=>{try{localStorage.setItem('flowforge-grid',$('grid-quality').value);}catch{}const u=new URL(location.href);u.searchParams.delete('grid');location.href=u.toString();};
 let forceTime=0;
 let frames=0,last=performance.now(),time=performance.now(),accumulator=0;
 function resize(){let w=$('viewport').clientWidth,h=$('viewport').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('viewport'));resize();
 function animate(now){requestAnimationFrame(animate);accumulator+=Math.min(now-time,100);time=now;if(running&&accumulator>=1000/30){solver.step();accumulator=0;}particleMat.uniforms.points.value=solver.particles[0].texture;smokeUniforms.density.value=solver.dye[0].texture;controls.update();renderer.render(scene,camera);frames++;if(now-forceTime>2000){const f=solver.forces(selected);$('drag').textContent=shapes.length?`Drag proxy ${f.total.toFixed(3)} (pressure ${f.pressure.toFixed(3)}, shear ${f.friction.toFixed(3)})`:'No obstacle selected';forceTime=now;}if(now-last>1000){$('stats').textContent=`${Math.round(frames*1000/(now-last))} fps · ${shapes.length} obstacle${shapes.length===1?'':'s'} · ${solver.steps} steps`;last=now;frames=0;}}
 requestAnimationFrame(animate);window.flowforge={solver,shapes,renderer,diagnostics:()=>solver.diagnostics(),pause:()=>{running=false;}};
} catch(e){$('error').hidden=false;$('error').textContent=e.message;$('stats').textContent='GPU unavailable';console.error(e);}
