import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {FluidSolver,prelude} from './solver.js';
import './style.css';
import {makeShape,disposeShape,importGeometry,airfoilGeometry} from './shapes.js';
import {startBenchmark} from './benchmark-view.js';
const $=id=>document.getElementById(id);
try {
 const renderer=new THREE.WebGLRenderer({antialias:true});
 if(!renderer.capabilities.isWebGL2||!renderer.extensions.has('EXT_color_buffer_float'))throw new Error('This app needs WebGL2 and floating-point render targets. Use a recent desktop Chrome, Firefox, or Safari with hardware acceleration.');
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('viewport').appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#0a141e');const camera=new THREE.PerspectiveCamera(45,1,.1,500);camera.position.set(96,68,105);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(32,16,16);controls.enableDamping=true;
 scene.add(new THREE.AmbientLight('#9dbbcf',2));const light=new THREE.DirectionalLight('#ffffff',3);light.position.set(25,60,30);scene.add(light);
 const tunnel=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(64,32,32)),new THREE.LineBasicMaterial({color:'#284b60',transparent:true,opacity:.75}));tunnel.position.set(32,16,16);scene.add(tunnel);
 const grid=new THREE.GridHelper(64,16,'#294b5c','#193142');grid.position.set(32,0,16);scene.add(grid);
 const arrow=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(-5,16,16),9,'#68e1b6',2,1);scene.add(arrow);
 const solver=new FluidSolver(renderer);const shapes=[];let selected=0;let running=true;let serial=0;
 const meshFor=makeShape;
 function refresh(reset=true){shapes.forEach(s=>{if(s.mesh){scene.remove(s.mesh);disposeShape(s.mesh);}s.mesh=meshFor(s);scene.add(s.mesh);});solver.setShapes(shapes);if(reset)solver.reset();$('selected').innerHTML=shapes.map((s,i)=>`<option value="${i}">${(s.label||s.type).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')} ${s.id}</option>`).join('');$('selected').value=selected;const s=shapes[selected];['size','position','height','depth','remove'].forEach(id=>$(id).disabled=!s);if(s){$('size').value=s.size;$('size-value').textContent=s.size;$('position').value=s.pos[0];$('height').value=s.pos[1];$('depth').value=s.pos[2];}$('add').disabled=shapes.length>=12;}
 function add(){if(shapes.length>=12)return;shapes.push({type:$('shape').value,geometry:$('shape').value==='airfoil'?airfoilGeometry():undefined,size:5,pos:[26+Math.min(shapes.length,3)*7,16,16],id:++serial});selected=shapes.length-1;refresh();}
 $('add').onclick=add;$('selected').onchange=e=>{selected=Number(e.target.value);refresh(false);};$('remove').onclick=()=>{const s=shapes[selected];if(!s)return;scene.remove(s.mesh);disposeShape(s.mesh);if(s.geometry)s.geometry.dispose();shapes.splice(selected,1);selected=Math.max(0,selected-1);refresh();};
 ['size','position','height','depth'].forEach((id,i)=>$(id).oninput=()=>{const s=shapes[selected];if(!s)return;if(i===0)s.size=+$(id).value;else s.pos[i-1]=+$(id).value;refresh();});
 $('speed').oninput=()=>{solver.inlet=+$('speed').value;$('speed-value').textContent=solver.inlet.toFixed(1);};$('viscosity').oninput=()=>{solver.viscosity=+$('viscosity').value;$('viscosity-value').textContent=solver.viscosity.toFixed(3);};$('toggle').onclick=()=>{running=!running;$('toggle').textContent=running?'Pause':'Run';$('state').textContent=running?'LIVE':'PAUSED';};$('reset').onclick=()=>solver.reset();
 add();
 const total=8192,geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(total*3),3));const ids=new Float32Array(total);for(let i=0;i<total;i++)ids[i]=i;geometry.setAttribute('pid',new THREE.BufferAttribute(ids,1));
 const particleMat=new THREE.ShaderMaterial({uniforms:{...solver.uniforms,points:{value:solver.particles[0].texture}},vertexShader:prelude+`uniform sampler2D points;attribute float pid;varying float speed;void main(){vec2 uv=vec2(mod(pid,128.)+.5,floor(pid/128.)+.5)/vec2(128.,64.);vec3 p=texture2D(points,uv).xyz;speed=length(linearVelocity(p));vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(150./-mv.z,1.5,4.);}`,fragmentShader:`precision highp float;varying float speed;void main(){if(length(gl_PointCoord-.5)>.5)discard;vec3 c=mix(vec3(.12,.4,.85),vec3(.32,.88,.73),clamp(speed,0.,1.));c=mix(c,vec3(1.,.91,.52),clamp(speed-1.,0.,1.));gl_FragColor=vec4(c,.78);}`,transparent:true,depthWrite:false});
 const points=new THREE.Points(geometry,particleMat);points.frustumCulled=false;scene.add(points);
 const trailGeo=new THREE.BufferGeometry();trailGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(total*6),3));const trailIds=new Float32Array(total*2),ends=new Float32Array(total*2);for(let i=0;i<total;i++){trailIds[i*2]=trailIds[i*2+1]=i;ends[i*2+1]=1;}trailGeo.setAttribute('pid',new THREE.BufferAttribute(trailIds,1));trailGeo.setAttribute('end',new THREE.BufferAttribute(ends,1));
 const trails=new THREE.LineSegments(trailGeo,new THREE.ShaderMaterial({uniforms:particleMat.uniforms,vertexShader:prelude+`uniform sampler2D points;attribute float pid;attribute float end;varying float speed;void main(){vec2 uv=vec2(mod(pid,128.)+.5,floor(pid/128.)+.5)/vec2(128.,64.);vec3 p=texture2D(points,uv).xyz;vec3 u=linearVelocity(p);speed=length(u);p-=u*end*.9;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`precision highp float;varying float speed;void main(){vec3 c=mix(vec3(.12,.4,.85),vec3(.32,.88,.73),clamp(speed,0.,1.));c=mix(c,vec3(1.,.91,.52),clamp(speed-1.,0.,1.));gl_FragColor=vec4(c,.28);}`,transparent:true,depthWrite:false}));trails.frustumCulled=false;scene.add(trails);
 let benchmarkMode=false,benchmarkWorker=null;
 $('mode').onchange=()=>{benchmarkMode=$('mode').value==='benchmark';$('benchmark-panel').hidden=!benchmarkMode;$('viewport').hidden=benchmarkMode;$('benchmark-viewport').hidden=!benchmarkMode;$('three-controls').hidden=benchmarkMode;$('stats').textContent=benchmarkMode?'2D LBM vorticity / CPU worker':'3D GPU flow';document.querySelector('.legend').hidden=benchmarkMode;document.querySelector('.hint').textContent=benchmarkMode?'Red / blue: opposite vorticity · Drag to orbit · Scroll to zoom':'Drag to orbit · Scroll to zoom · Flow left → right';if(benchmarkMode&&!benchmarkWorker)benchmarkWorker=startBenchmark();else benchmarkWorker?.postMessage({type:'pause',value:!benchmarkMode});};
 $('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Keep the file below 10 MB.');if(shapes.length>=12)throw Error('Remove a shape first.');$('import-status').textContent='Voxelizing...';const geometry=importGeometry(file.name,await file.arrayBuffer());shapes.push({type:'mesh',geometry,label:file.name.replace(/[<>]/g,''),size:5,pos:[26,16,16],id:++serial});selected=shapes.length-1;refresh();$('import-status').textContent='Imported. Closed/watertight meshes work best.';}catch(e){$('import-status').textContent=e.message;}$('import').value='';};
 let forceTime=0;
 let frames=0,last=performance.now(),time=performance.now(),accumulator=0;
 function resize(){let w=$('viewport').clientWidth,h=$('viewport').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('viewport'));resize();
 function animate(now){requestAnimationFrame(animate);accumulator+=Math.min(now-time,100);time=now;if(running&&!benchmarkMode&&accumulator>=1000/30){solver.step();accumulator=0;}particleMat.uniforms.points.value=solver.particles[0].texture;controls.update();if(!benchmarkMode)renderer.render(scene,camera);frames++;if(!benchmarkMode&&now-forceTime>2000){const f=solver.forces(selected);$('drag').textContent=shapes.length?`Drag proxy ${f.total.toFixed(3)} (pressure ${f.pressure.toFixed(3)}, shear ${f.friction.toFixed(3)})`:'No obstacle selected';forceTime=now;}if(now-last>1000&&!benchmarkMode){$('stats').textContent=`${Math.round(frames*1000/(now-last))} fps · ${shapes.length} obstacle${shapes.length===1?'':'s'} · ${solver.steps} steps`;last=now;frames=0;}}
 requestAnimationFrame(animate);window.flowforge={solver,shapes,renderer,diagnostics:()=>solver.diagnostics(),pause:()=>{running=false;}};
} catch(e){$('error').hidden=false;$('error').textContent=e.message;$('stats').textContent='GPU unavailable';console.error(e);}
