import {S,NX,NY,NZ,W,H} from './grid.js';
import * as THREE from 'three';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
export function composite(type){const parts=[];const box=(p,d,c)=>parts.push({type:'box',p,d,c});const ell=(p,d,c)=>parts.push({type:'sphere',p,d,c});const wheel=(p,r=.22)=>ell(p,[r,r,r],'#18232b');
 if(type==='car'){box([0,0,0],[2.2,.55,1],'#69b5d3');box([-.2,.45,0],[1.1,.5,.88],'#9fd7e2');for(let x of [-.7,.7])for(let z of [-.52,.52])wheel([x,-.2,z]);box([1.12,.05,0],[.04,.16,.75],'#fff4ba');}
 if(type==='f1'){box([-.2,0,0],[1.5,.3,.48],'#e35a5a');box([.9,-.04,0],[1,.14,.22],'#e35a5a');ell([-.25,.27,0],[.26,.2,.23],'#222d38');for(let x of [-.85,.85])for(let z of [-.55,.55])wheel([x,-.08,z],.3);box([1.35,-.08,0],[.22,.12,1.5],'#e35a5a');box([-1.05,.48,0],[.3,.1,1.4],'#e35a5a');box([-1.05,.15,0],[.1,.6,.5],'#e35a5a');}
 if(type==='cow'){ell([0,.25,0],[1.1,.58,.47],'#e5e9df');ell([.96,.35,0],[.45,.38,.4],'#e5e9df');box([1.3,.25,0],[.2,.22,.48],'#e6acb0');for(let x of [-.65,.65])for(let z of [-.28,.28])box([x,-.48,z],[.17,.8,.16],'#e5e9df');for(let z of [-.4,.4])ell([.98,.62,z],[.28,.1,.16],'#1a2730');for(let z of [-.23,.23])box([.95,.86,z],[.08,.3,.08],'#ece3bb');box([-1.08,.05,0],[.07,.7,.07],'#e5e9df');ell([-.4,.4,.4],[.35,.3,.12],'#18232b');ell([.25,.5,-.35],[.28,.28,.14],'#18232b');for(let z of [-.35,.35])ell([1.12,.52,z],[.05,.05,.05],'#080b10');}
 // Nose/head points upstream (-X); same mirrored parts drive render and voxel mask.
 for(const part of parts)part.p[0]=-part.p[0];
 return parts;
}
export function airfoilGeometry(){const points=[];function t(x){return 5*.12*(.2969*Math.sqrt(x)-.126*x-.3516*x*x+.2843*x*x*x-.1036*x*x*x*x);}for(let i=0;i<=80;i++){let x=(1-Math.cos(Math.PI*i/80))/2;points.push(new THREE.Vector2((x-.5)*2,t(x)*2));}for(let i=79;i>0;i--){let x=(1-Math.cos(Math.PI*i/80))/2;points.push(new THREE.Vector2((x-.5)*2,-t(x)*2));}const geometry=new THREE.ExtrudeGeometry(new THREE.Shape(points),{depth:1.4,bevelEnabled:false,steps:1});geometry.translate(0,0,-.7);return geometry.toNonIndexed();}
export function rotationQuaternion(angles=[0,0,0]){return new THREE.Quaternion().setFromEuler(new THREE.Euler(...angles.map(a=>a*Math.PI/180),'XYZ'));}
export function makeShape(s){const m=makeUnrotatedShape(s);m.quaternion.premultiply(rotationQuaternion(s.rotation));return m;}
function makeUnrotatedShape(s){if(s.type==='golf'){const g=new THREE.SphereGeometry(s.size,80,60),p=g.attributes.position,v=new THREE.Vector3();const centers=[];for(let i=0;i<240;i++){let y=1-2*(i+.5)/240,r=Math.sqrt(1-y*y),t=i*2.399963;centers.push(new THREE.Vector3(r*Math.cos(t),y,r*Math.sin(t)));}for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).normalize();let dist=2;for(let c of centers)dist=Math.min(dist,v.distanceTo(c));let dip=dist<.09?.024*(1-dist*dist/(.09*.09)):0;v.multiplyScalar(s.size*(1-dip));p.setXYZ(i,v.x,v.y,v.z);}g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:'#f0f3ed',roughness:.7}));m.position.set(...s.pos);return m;}if(s.type==='mesh'||s.type==='airfoil'){let mesh=new THREE.Mesh(s.geometry.clone(),new THREE.MeshStandardMaterial({color:'#b7dbe5',roughness:.5,side:THREE.DoubleSide}));mesh.scale.setScalar(s.size);mesh.position.set(...s.pos);return mesh;}if(['car','f1','cow'].includes(s.type)){let group=new THREE.Group();for(let part of composite(s.type)){let g=part.type==='box'?new THREE.BoxGeometry(...part.d):new THREE.SphereGeometry(1,24,16);const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:part.c,roughness:.5}));if(part.type==='sphere')mesh.scale.set(...part.d);mesh.position.set(...part.p);group.add(mesh);}group.scale.setScalar(s.size);group.position.set(...s.pos);return group;}const g=s.type==='sphere'?new THREE.SphereGeometry(s.size,32,20):s.type==='box'?new THREE.BoxGeometry(s.size*2,s.size*2,s.size*2):new THREE.CylinderGeometry(s.size,s.size,s.size*3,32);const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:'#e0eeef',metalness:.25,roughness:.3}));mesh.position.set(...s.pos);return mesh;}
export function disposeShape(m){m.traverse(x=>{x.geometry?.dispose();if(x.material)x.material.dispose();});}
export function importGeometry(name,buffer){let geometry;if(/\.stl$/i.test(name))geometry=new STLLoader().parse(buffer);else if(/\.obj$/i.test(name)){const obj=new OBJLoader().parse(new TextDecoder().decode(buffer)),positions=[];obj.updateMatrixWorld(true);obj.traverse(m=>{if(m.isMesh){const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry,p=g.attributes.position,v=new THREE.Vector3();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(m.matrixWorld);positions.push(v.x,v.y,v.z);}}});geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));}else throw Error('Choose an STL or OBJ file.');if(!geometry.attributes.position?.count)throw Error('No triangles found.');if(geometry.attributes.position.count>180000)throw Error('Mesh too large. Simplify below 60,000 triangles.');if(geometry.index)geometry=geometry.toNonIndexed();const a=geometry.attributes.position.array;if(!Array.from(a).every(Number.isFinite))throw Error('Invalid vertex coordinates.');geometry.computeBoundingBox();const size=geometry.boundingBox.getSize(new THREE.Vector3()),scale=Math.max(size.x,size.y,size.z);if(scale<=0)throw Error('Mesh has no volume.');const center=geometry.boundingBox.getCenter(new THREE.Vector3());geometry.translate(-center.x,-center.y,-center.z);geometry.scale(2/scale,2/scale,2/scale);geometry.computeVertexNormals();return geometry;}
export function voxelMask(shapes){const data=new Float32Array(W*H*4),owners=new Int16Array(NX*NY*NZ);owners.fill(-1);const ray=new THREE.Ray(new THREE.Vector3(),new THREE.Vector3(1,0,0)),a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),hit=new THREE.Vector3();for(let si=0;si<shapes.length;si++){const s=shapes[si],parts=composite(s.type),p=s.geometry?.attributes.position,inverse=rotationQuaternion(s.rotation).invert(),local=new THREE.Vector3();for(let z=1;z<NZ-1;z++)for(let y=1;y<NY-1;y++)for(let x=1;x<NX-1;x++){const d=local.set((x+.5-S*s.pos[0])/(S*s.size),(y+.5-S*s.pos[1])/(S*s.size),(z+.5-S*s.pos[2])/(S*s.size)).applyQuaternion(inverse).toArray();let solid=false;if((s.type==='sphere'||s.type==='golf'))solid=Math.hypot(...d)<1;else if(s.type==='box')solid=Math.max(...d.map(Math.abs))<1;else if(s.type==='cylinder')solid=Math.hypot(d[0],d[2])<1&&Math.abs(d[1])<1.5;else if(s.type==='mesh'||s.type==='airfoil'){if(Math.max(...d.map(Math.abs))<=1.001){ray.origin.set(d[0],d[1]+.000013,d[2]+.000017);let ts=[];for(let t=0;t<p.count;t+=3){a.fromBufferAttribute(p,t);b.fromBufferAttribute(p,t+1);c.fromBufferAttribute(p,t+2);if(ray.intersectTriangle(a,b,c,false,hit)){const dist=hit.x-d[0];if(dist>1e-6&&!ts.some(v=>Math.abs(v-dist)<1e-5))ts.push(dist);}}solid=ts.length%2===1;}}else{solid=parts.some(part=>{const q=d.map((v,i)=>(v-part.p[i])/part.d[i]);return part.type==='box'?Math.max(...q.map(Math.abs))<.5:Math.hypot(...q)<1;});}if(solid){const i=(z*NY+y)*NX+x;owners[i]=si;data[((Math.floor(z/8)*NY+y)*W+(z%8)*NX+x)*4]=1;}}}return {data,owners};}
