import * as THREE from 'three';
import {voxelMask} from './shapes.js';
import {S,NX,NY,NZ,W,H} from './grid.js';
export const GRID = [NX,NY,NZ];
const prelude = `precision highp float;
uniform sampler2D velocity, pressure, source, solidMask;
uniform vec4 obstacles[12];
uniform vec4 kinds[12];
uniform int count;
uniform float inlet, viscosity, dt, confinement;
varying vec2 vUv;
const vec3 N=vec3(${NX}.,${NY}.,${NZ}.);
vec2 uv3(vec3 p){p=clamp(p,vec3(.5),N-.5);float z=floor(p.z);return (vec2(mod(z,8.)*${NX}.,floor(z/8.)*${NY}.)+p.xy)/vec2(${W}.,${H}.);}
vec3 cell(){vec2 q=floor(vUv*vec2(${W}.,${H}.));return vec3(mod(q.x,${NX}.),mod(q.y,${NY}.),floor(q.x/${NX}.)+8.*floor(q.y/${NY}.))+.5;}
vec4 at(sampler2D t,vec3 p){return texture2D(t,uv3(p));}
vec3 linearVelocity(vec3 p){vec3 b=floor(p-.5)+.5;vec3 f=fract(p-.5);return mix(mix(mix(at(velocity,b).xyz,at(velocity,b+vec3(1,0,0)).xyz,f.x),mix(at(velocity,b+vec3(0,1,0)).xyz,at(velocity,b+vec3(1,1,0)).xyz,f.x),f.y),mix(mix(at(velocity,b+vec3(0,0,1)).xyz,at(velocity,b+vec3(1,0,1)).xyz,f.x),mix(at(velocity,b+vec3(0,1,1)).xyz,at(velocity,b+vec3(1,1,1)).xyz,f.x),f.y),f.z);}
vec3 lin(sampler2D t,vec3 p){vec3 b=floor(p-.5)+.5;vec3 f=fract(p-.5);return mix(mix(mix(at(t,b).xyz,at(t,b+vec3(1,0,0)).xyz,f.x),mix(at(t,b+vec3(0,1,0)).xyz,at(t,b+vec3(1,1,0)).xyz,f.x),f.y),mix(mix(at(t,b+vec3(0,0,1)).xyz,at(t,b+vec3(1,0,1)).xyz,f.x),mix(at(t,b+vec3(0,1,1)).xyz,at(t,b+vec3(1,1,1)).xyz,f.x),f.y),f.z);}
bool solid(vec3 p){if(at(solidMask,p).r>.5)return true;for(int i=0;i<12;i++){if(i>=count)break;vec3 d=p-obstacles[i].xyz;float r=obstacles[i].w;float k=kinds[i].x;if(k<.5&&length(d)<r)return true;if(k>.5&&k<1.5&&max(max(abs(d.x),abs(d.y)),abs(d.z))<r)return true;if(k>1.5&&length(d.xz)<r&&abs(d.y)<r*1.5)return true;}return false;}
bool wall(vec3 p){return p.y<1.||p.y>${NY-1}.||p.z<1.||p.z>${NZ-1}.;}
vec3 vel(vec3 p){if(wall(p)){vec3 q=p,m=vec3(1);if(p.y<1.){q.y=2.-p.y;m.y=-1.;}else if(p.y>${NY-1}.){q.y=${2*(NY-1)}.-p.y;m.y=-1.;}if(p.z<1.){q.z=2.-p.z;m.z=-1.;}else if(p.z>${NZ-1}.){q.z=${2*(NZ-1)}.-p.z;m.z=-1.;}return at(velocity,q).xyz*m;}if(solid(p))return vec3(0);if(p.x<1.)return vec3(inlet,0,0);return at(velocity,p).xyz;}
`;
const vertex = `varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`;
export class FluidSolver {
 constructor(renderer){
  this.renderer=renderer; this.steps=0;this.inlet=1;this.viscosity=.02;this.dt=.45;this.confinement=.18;
  this.scene=new THREE.Scene();this.camera=new THREE.Camera();this.quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2));this.scene.add(this.quad);
  const target=(w=W,h=H)=>new THREE.WebGLRenderTarget(w,h,{type:THREE.FloatType,format:THREE.RGBAFormat,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:false,stencilBuffer:false});
  this.v=[target(),target()];this.p=[target(),target()];this.div=target();this.curl=target();this.curl.texture.minFilter=THREE.LinearFilter;this.curl.texture.magFilter=THREE.LinearFilter;this.dye=[target(),target()];this.hatT=target();this.useMac=true;this.macK=.15;this.iters=S===1?24:40;this.dye.forEach(t=>{t.texture.minFilter=THREE.LinearFilter;t.texture.magFilter=THREE.LinearFilter;});this.particles=[target(128,64),target(128,64)];
  this.maskTexture=new THREE.DataTexture(new Float32Array(W*H*4),W,H,THREE.RGBAFormat,THREE.FloatType);this.maskTexture.needsUpdate=true;
  this.uniforms={solidMask:{value:this.maskTexture},velocity:{value:null},pressure:{value:null},source:{value:null},obstacles:{value:Array.from({length:12},()=>new THREE.Vector4())},kinds:{value:Array.from({length:12},()=>new THREE.Vector4())},count:{value:0},inlet:{value:1},viscosity:{value:.02},dt:{value:.45},confinement:{value:.18},curlField:{value:this.curl.texture},hat:{value:null},macK:{value:.15},density:{value:null},smokeSource:{value:new THREE.Vector4(18*S,16*S,16*S,6*S)}};
  const material=body=>new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:prelude+body,uniforms:this.uniforms});
  this.init=material(`void main(){vec3 p=cell();gl_FragColor=vec4(solid(p)?vec3(0):vec3(inlet,0,0),1);}`);
  this.zero=material(`void main(){gl_FragColor=vec4(0);}`);
  this.advect=material(`void main(){vec3 p=cell();vec3 u=linearVelocity(p-dt*vel(p));vec3 lap=vel(p+vec3(1,0,0))+vel(p-vec3(1,0,0))+vel(p+vec3(0,1,0))+vel(p-vec3(0,1,0))+vel(p+vec3(0,0,1))+vel(p-vec3(0,0,1))-6.*vel(p);u+=viscosity*dt*lap;if(p.x<2.)u=vec3(inlet,0,0);if(solid(p))u=vec3(0);else if(wall(p))u=vel(p);gl_FragColor=vec4(u,1);}`);
  this.advHat=material(`void main(){vec3 p=cell();vec3 u=vel(p);gl_FragColor=vec4(linearVelocity(p-dt*u),1);}`);
  this.mac=material(`uniform sampler2D hat;uniform float macK;void main(){vec3 p=cell();vec3 u=vel(p);vec3 q=p-dt*u;vec3 h=at(hat,p).xyz;vec3 back=lin(hat,p+dt*u);vec3 n=at(velocity,p).xyz;vec3 r=h+macK*(n-back);vec3 b=floor(q-.5)+.5;vec3 mn=vec3(1e9),mx=vec3(-1e9);for(int i=0;i<8;i++){vec3 o=vec3(float(i&1),float((i>>1)&1),float((i>>2)&1));vec3 c=at(velocity,b+o).xyz;mn=min(mn,c);mx=max(mx,c);}r=clamp(r,mn,mx);vec3 lap=vel(p+vec3(1,0,0))+vel(p-vec3(1,0,0))+vel(p+vec3(0,1,0))+vel(p-vec3(0,1,0))+vel(p+vec3(0,0,1))+vel(p-vec3(0,0,1))-6.*vel(p);r+=viscosity*dt*lap;if(p.x<2.)r=vec3(inlet,0,0);if(solid(p))r=vec3(0);else if(wall(p))r=vel(p);gl_FragColor=vec4(r,1);}`);
  this.curlPass=material(`void main(){vec3 p=cell(),xp=vel(p+vec3(1,0,0)),xm=vel(p-vec3(1,0,0)),yp=vel(p+vec3(0,1,0)),ym=vel(p-vec3(0,1,0)),zp=vel(p+vec3(0,0,1)),zm=vel(p-vec3(0,0,1));vec3 w=.5*vec3(yp.z-ym.z-zp.y+zm.y,zp.x-zm.x-xp.z+xm.z,xp.y-xm.y-yp.x+ym.x);gl_FragColor=vec4(w,length(w));}`);
  this.confine=material(`uniform sampler2D curlField;void main(){vec3 p=cell();vec3 g=.5*vec3(at(curlField,p+vec3(1,0,0)).w-at(curlField,p-vec3(1,0,0)).w,at(curlField,p+vec3(0,1,0)).w-at(curlField,p-vec3(0,1,0)).w,at(curlField,p+vec3(0,0,1)).w-at(curlField,p-vec3(0,0,1)).w);vec3 force=confinement*cross(g/(length(g)+.0001),at(curlField,p).xyz);vec3 u=vel(p)+dt*force;u=clamp(u,vec3(-${3*S}.),vec3(${3*S}.));if(p.x<2.)u=vec3(inlet,0,0);if(solid(p))u=vec3(0);else if(wall(p))u=vel(p);gl_FragColor=vec4(u,1);}`);
  this.smoke=material(`uniform sampler2D density;uniform vec4 smokeSource;
float sampleD(vec3 p){vec3 b=floor(p-.5)+.5,f=fract(p-.5);return mix(mix(mix(at(density,b).x,at(density,b+vec3(1,0,0)).x,f.x),mix(at(density,b+vec3(0,1,0)).x,at(density,b+vec3(1,1,0)).x,f.x),f.y),mix(mix(at(density,b+vec3(0,0,1)).x,at(density,b+vec3(1,0,1)).x,f.x),mix(at(density,b+vec3(0,1,1)).x,at(density,b+vec3(1,1,1)).x,f.x),f.y),f.z);}
void main(){vec3 p=cell();float d=sampleD(p-dt*vel(p))*${1-.003/S};float r=length(p.yz-smokeSource.yz)/max(smokeSource.w,1.);float jet=exp(-r*r*2.);float ribbons=.55+.45*cos((p.y-smokeSource.y)*${1.5/S})*cos((p.z-smokeSource.z)*${1.5/S});if(abs(p.x-smokeSource.x)<1.2)d=max(d,jet*ribbons*.9);if(solid(p)||p.x>${NX-1}.)d=0.;gl_FragColor=vec4(d,0,0,1);}`);
  this.divergence=material(`void main(){vec3 p=cell();float d=.5*(vel(p+vec3(1,0,0)).x-vel(p-vec3(1,0,0)).x+vel(p+vec3(0,1,0)).y-vel(p-vec3(0,1,0)).y+vel(p+vec3(0,0,1)).z-vel(p-vec3(0,0,1)).z);gl_FragColor=vec4((solid(p)||wall(p))?0.:d,0,0,1);}`);
  this.jacobi=material(`float pr(vec3 q,vec3 p){if(q.x>${NX-1}.)return 0.;if(q.x<1.||solid(q)||wall(q))return at(pressure,p).x;return at(pressure,q).x;}void main(){vec3 p=cell();float s=pr(p+vec3(1,0,0),p)+pr(p-vec3(1,0,0),p)+pr(p+vec3(0,1,0),p)+pr(p-vec3(0,1,0),p)+pr(p+vec3(0,0,1),p)+pr(p-vec3(0,0,1),p);gl_FragColor=vec4((solid(p)||wall(p))?0.:(s-at(source,p).x)/6.,0,0,1);}`);
  this.project=material(`float pr(vec3 q,vec3 p){if(q.x>${NX-1}.)return 0.;if(q.x<1.||solid(q)||wall(q))return at(pressure,p).x;return at(pressure,q).x;}void main(){vec3 p=cell();vec3 g=.5*vec3(pr(p+vec3(1,0,0),p)-pr(p-vec3(1,0,0),p),pr(p+vec3(0,1,0),p)-pr(p-vec3(0,1,0),p),pr(p+vec3(0,0,1),p)-pr(p-vec3(0,0,1),p));vec3 u=vel(p)-g;if(p.x<2.)u=vec3(inlet,0,0);if(solid(p))u=vec3(0);else if(wall(p))u=vel(p);gl_FragColor=vec4(u,1);}`);
  this.seed=material(`float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec3 p=vec3(2.+${NX-4}.*hash(vUv),3.+${NY-6}.*hash(vUv+1.),3.+${NZ-6}.*hash(vUv+2.));gl_FragColor=vec4(p,hash(vUv+3.)*160.);}`);
  this.move=material(`float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec4 a=texture2D(source,vUv);vec3 p=a.xyz;vec3 u=linearVelocity(p);p+=dt*linearVelocity(p+.5*dt*u);float age=a.w+dt;if(p.x>${NX-2}.||p.y<2.||p.y>${NY-2}.||p.z<2.||p.z>${NZ-2}.||solid(p)||age>180.){p=vec3(2.,3.+${NY-6}.*hash(vUv+age*.001),3.+${NZ-6}.*hash(vUv+age*.002+2.));age=0.;}gl_FragColor=vec4(p,age);}`);
 }
 pass(mat,target){this.quad.material=mat;this.renderer.setRenderTarget(target);this.renderer.render(this.scene,this.camera);this.renderer.setRenderTarget(null);}
 setShapes(shapes){const mask=voxelMask(shapes);this.owners=mask.owners;this.maskTexture.image.data=mask.data;this.maskTexture.needsUpdate=true;this.uniforms.count.value=0;this.uniforms.smokeSource.value.set(4*S,16*S,16*S,14*S);shapes.forEach((s,i)=>{this.uniforms.obstacles.value[i].set(s.pos[0]*S,s.pos[1]*S,s.pos[2]*S,s.size*S);this.uniforms.kinds.value[i].x={sphere:0,box:1,cylinder:2}[s.type]||0;});}
 reset(){this.uniforms.inlet.value=this.inlet*S;this.pass(this.init,this.v[0]);this.pass(this.init,this.v[1]);this.pass(this.zero,this.p[0]);this.pass(this.zero,this.p[1]);this.pass(this.seed,this.particles[0]);this.pass(this.seed,this.particles[1]);this.pass(this.zero,this.curl);this.pass(this.zero,this.dye[0]);this.pass(this.zero,this.dye[1]);this.steps=0;}
 step(){const u=this.uniforms;u.inlet.value=this.inlet*S;u.viscosity.value=this.viscosity*S*S;u.confinement.value=this.confinement*S;u.velocity.value=this.v[0].texture;if(this.useMac){this.pass(this.advHat,this.hatT);u.hat.value=this.hatT.texture;u.macK.value=this.macK;this.pass(this.mac,this.v[1]);}else this.pass(this.advect,this.v[1]);this.v.reverse();u.velocity.value=this.v[0].texture;if(this.confinement>0){this.pass(this.curlPass,this.curl);this.pass(this.confine,this.v[1]);this.v.reverse();u.velocity.value=this.v[0].texture;}this.pass(this.divergence,this.div);u.source.value=this.div.texture;for(let i=0;i<this.iters;i++){u.pressure.value=this.p[0].texture;this.pass(this.jacobi,this.p[1]);this.p.reverse();}u.pressure.value=this.p[0].texture;this.pass(this.project,this.v[1]);this.v.reverse();u.velocity.value=this.v[0].texture;this.pass(this.curlPass,this.curl);u.density.value=this.dye[0].texture;this.pass(this.smoke,this.dye[1]);this.dye.reverse();u.density.value=this.dye[0].texture;u.source.value=this.particles[0].texture;this.pass(this.move,this.particles[1]);this.particles.reverse();this.steps++;}
 forces(selected){const v=new Float32Array(W*H*4),p=new Float32Array(v.length);this.renderer.readRenderTargetPixels(this.v[0],0,0,W,H,v);this.renderer.readRenderTargetPixels(this.p[0],0,0,W,H,p);const idx=(x,y,z)=>((Math.floor(z/8)*NY+y)*W+(z%8)*NX+x)*4;let pressure=0,friction=0,faces=0;for(let z=1;z<NZ-1;z++)for(let y=1;y<NY-1;y++)for(let x=1;x<NX-1;x++){if(this.owners[(z*NY+y)*NX+x]!==selected)continue;for(let d of [[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]){let [a,b,c]=[x+d[0],y+d[1],z+d[2]];if(this.owners[(c*NY+b)*NX+a]>=0)continue;let i=idx(a,b,c);pressure-=p[i]*d[0];friction+=this.viscosity*v[i]*(1-Math.abs(d[0]));faces++;}}const kp=1/(S**4),kf=1/(S**3);return {pressure:pressure*kp,friction:friction*kf,total:pressure*kp+friction*kf,faces};}
 diagnostics(){const a=new Float32Array(W*H*4);this.renderer.readRenderTargetPixels(this.v[0],0,0,W,H,a);let max=0,sum=0,finite=true;for(let i=0;i<a.length;i+=4){let m=Math.hypot(a[i],a[i+1],a[i+2]);finite&&=Number.isFinite(m);sum+=m;max=Math.max(max,m);}return {finite,max:max/S,mean:sum/(NX*NY*NZ)/S,steps:this.steps};}
}
export {prelude};
